### ISSUE TITLE
Had you seen the GORB (go routing and balancing) project & its use of Consul?

### ISSUE THREAD

**Issue by bmullan** [mr-io/lxd-consul#1]
I haven't tried your Consul LXD script yet but thought I'd ask if you'd seen this project called GORB (Go Routing and Balancing) which uses Consul?   The gorb author works for Uber and gave a Docker preso on using gorb & consul with Docker containers.   Seems like this could be done for LXD containers as well?

https://github.com/kobolog/gorb

Brian

**Comment by mar-io** [comment]
Thanks for bringing that to my attention. Haven't heard of it. I made a cursory glance through the project and I think it allows you to pass your consul endpoint as a parameter(-c). So you should be able to create a consul cluster using this and pass your endpoints to GORB.
